services:
  db:
    image: postgres:18-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=sunjinlee"
      - "POSTGRES_DB=dart"
    volumes:
      - db-volume:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - dart-local-network

  redis:
    image: redis/redis-stack-server:7.4.0-v8
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - dart-local-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    env_file:
      - .env.docker
    networks:
      - dart-local-network
    depends_on:
      - db
      - redis

  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - 8080:8080
    env_file:
      - .env.docker
    networks:
      - dart-local-network
    depends_on:
      - db
      - redis

networks:
  dart-local-network:
    name: dart-local-network
    driver: bridge

volumes:
  db-volume:
  redis-data:
