# syntax=docker/dockerfile:1

FROM golang:1.25-alpine AS builder
WORKDIR /app

RUN apk add --no-cache ca-certificates git
COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal

RUN CGO_ENABLED=0 \
	go build -trimpath -ldflags "-s -w" -o /out/api ./cmd/api

FROM alpine:3.20
WORKDIR /app

RUN apk add --no-cache ca-certificates \
	&& adduser -D -g '' appuser

COPY --from=builder /out/api ./api

USER appuser
EXPOSE 8080
ENTRYPOINT ["./api"]
