# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZubN7GXxqEeFvgYm3WlInbA396m3Qhy
"""

!wget "https://raw.githubusercontent.com/kho126942-a11y/makemore/refs/heads/master/names.txt"
# 깃허브 makemore에서 names.txt파일에 들어가 raw를 누르고 링크를 얻는다.

words = open("names.txt").read().splitlines()

chars = sorted(list(set("".join(words))))
chars = ["."] + chars

stoi = {s:i for i,s in enumerate(chars)}
itos = {i:s for s,i in stoi.items()}

"""Lesson 2"""

import torch

# create the training set of bigrams (x,y)
xs, ys = [], []

for w in words[:1]:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):  #zip은 남으면 버린다. ex) .emma.  emma.이기에 2묶음씩 묶어서 앞의 .이 남는데 이것은 버려진다.
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    print(ch1, ch2)
    xs.append(ix1)  #
    ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

xs

ys

"""lesson 3"""

# build the dataset

block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words:

  #print(w)
  context = [0] * block_size
  for ch in w + '.': # ch에는 e가 들어가 있다. w의 첫번째 글자
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    #print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # crop and append

X = torch.tensor(X)
Y = torch.tensor(Y)

"""... -> e
..e -> m
.em -> m
emm -> a
mma -> .

... = 000 -> e =5
..e = 005
"""

X

Y

"""블럭 사이즈를 1로 하면 lesson 2의 코드가 되고
3으로 하면 lesson 3의 코드가 된다.

NEW CORD
"""



"""class _______ #dataset
dataset에는 3가지가 있다.
def __init__
def __len__
def __getitem__   #index의 인자를 받는다.
"""