"""Python Code Exporter.

StrategyDefinition을 Python DSL 코드로 변환합니다.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional, Set, Union

from kis_backtest.core.strategy import StrategyDefinition
from kis_backtest.file.schema import KisStrategyFile


# 지표 ID -> DSL 함수 이름 매핑
INDICATOR_DSL_MAP = {
    # 이동평균
    "sma": "SMA",
    "ema": "EMA",
    "dema": "DEMA",
    "tema": "TEMA",
    "hma": "HMA",
    "kama": "KAMA",
    "alma": "ALMA",
    "lwma": "LWMA",
    "trima": "TRIMA",
    "t3": "T3",
    "zlema": "ZLEMA",
    "wma": "WMA",
    "frama": "FRAMA",
    "vidya": "VIDYA",
    # 오실레이터
    "rsi": "RSI",
    "stochastic": "STOCHASTIC",
    "stochrsi": "STOCHRSI",
    "macd": "MACD",
    "cci": "CCI",
    "williams_r": "WILLIAMS_R",
    "momentum": "MOMENTUM",
    "roc": "ROC",
    "apo": "APO",
    "ppo": "PPO",
    "aroon": "AROON",
    "cmo": "CMO",
    "ao": "AO",
    "cho": "CHO",
    "ultosc": "ULTOSC",
    "trix": "TRIX",
    "tsi": "TSI",
    "rvi": "RVI",
    "dpo": "DPO",
    "kvo": "KVO",
    # 추세
    "adx": "ADX",
    "adxr": "ADXR",
    "ichimoku": "IchimokuCloud",
    "sar": "SAR",
    "vortex": "VORTEX",
    "chop": "CHOP",
    "kst": "KST",
    "coppock": "COPPOCK",
    "supertrend": "SUPERTREND",
    "mass_index": "MASS_INDEX",
    "schaff": "SCHAFF",
    "fisher": "FISHER",
    # 거래량
    "obv": "OBV",
    "ad": "AD",
    "adl": "ADL",
    "cmf": "CMF",
    "mfi": "MFI",
    "force": "FORCE",
    "vwap": "VWAP",
    "vwma": "VWMA",
    "eom": "EOM",
    # 변동성
    "atr": "ATR",
    "natr": "NATR",
    "bollinger": "BB",
    "keltner": "KeltnerChannels",
    "donchian": "DonchianChannel",
    "std": "STD",
    "variance": "VARIANCE",
    "accbands": "AccelerationBands",
    "beta": "BETA",
    "alpha": "ALPHA",
    # 기타
    "maximum": "MAXIMUM",
    "minimum": "MINIMUM",
    "midpoint": "MIDPOINT",
    "midprice": "MIDPRICE",
    "logr": "LOGR",
    "ibs": "IBS",
    "bop": "BOP",
    "regression": "REGRESSION",
    "pivot": "PIVOT",
    "augen": "AUGEN",
}

# 멀티 아웃풋 지표 목록
MULTI_OUTPUT_INDICATORS = {
    "bollinger": {"upper", "middle", "lower"},
    "macd": {"value", "signal", "histogram"},
    "stochastic": {"k", "d"},
    "stochrsi": {"k", "d"},
    "ichimoku": {"tenkan", "kijun", "senkou_a", "senkou_b", "chikou"},
    "keltner": {"upper", "middle", "lower"},
    "donchian": {"upper", "lower"},
    "accbands": {"upper", "middle", "lower"},
    "adx": {"value", "plus_di", "minus_di"},
    "aroon": {"value", "aroon_up", "aroon_down"},
    "vortex": {"plus_vi", "minus_vi"},
    "ppo": {"value", "signal", "histogram"},
    "tsi": {"value", "signal"},
    "kst": {"value", "signal"},
    "kvo": {"value", "signal"},
    "regression": {"value", "slope", "intercept"},
    "pivot": {"high", "low"},
}

# 연산자 -> Python 연산자 매핑
OPERATOR_MAP = {
    "greater_than": ">",
    "less_than": "<",
    "greater_equal": ">=",
    "less_equal": "<=",
    "equal": "==",
    "cross_above": ".crosses_above",
    "cross_below": ".crosses_below",
}


class PythonExporter:
    """전략을 Python DSL 코드로 변환

    StrategyDefinition 또는 KisStrategyFile을 실행 가능한
    Python 코드 문자열로 변환합니다.

    Example:
        definition = StrategyRegistry.build("sma_crossover")
        python_code = PythonExporter.to_python_string(definition)
        print(python_code)
    """

    @staticmethod
    def to_python_string(obj: Union[StrategyDefinition, KisStrategyFile]) -> str:
        """전략을 Python 코드 문자열로 변환

        Args:
            obj: StrategyDefinition 또는 KisStrategyFile

        Returns:
            실행 가능한 Python 코드 문자열
        """
        if isinstance(obj, KisStrategyFile):
            definition = obj.to_strategy_definition()
            metadata_name = obj.metadata.name
            metadata_desc = obj.metadata.description
        else:
            definition = obj
            metadata_name = definition.name
            metadata_desc = definition.description

        # 필요한 import 수집
        imports = PythonExporter._collect_imports(definition)

        # 코드 생성
        lines = []

        # 헤더
        lines.append(f'# === {definition.id}.py ===')
        lines.append('# Generated by KIS Backtest')
        lines.append(f'# Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        # Imports
        lines.append('from kis_backtest.dsl import (')
        lines.append('    RuleBuilder,')
        for imp in sorted(imports):
            lines.append(f'    {imp},')
        lines.append(')')
        lines.append('')

        # 지표 인스턴스 (멀티 아웃풋만)
        indicator_vars = PythonExporter._generate_indicator_vars(definition)
        if indicator_vars:
            lines.append('# Indicators')
            lines.extend(indicator_vars)
            lines.append('')

        # 전략 빌드
        lines.append('# Strategy Definition')
        lines.append('strategy = (')
        lines.append(f'    RuleBuilder("{definition.id}")')
        lines.append(f'    .description("{metadata_desc}")')
        lines.append(f'    .category("{definition.category}")')

        # 진입 조건
        entry_code = PythonExporter._generate_condition_code(definition.entry, definition.indicators)
        lines.append(f'    .buy_when({entry_code})')

        # 청산 조건
        exit_code = PythonExporter._generate_condition_code(definition.exit, definition.indicators)
        lines.append(f'    .sell_when({exit_code})')

        # 리스크 관리
        risk = definition.risk_management
        if risk.get("stop_loss_pct"):
            lines.append(f'    .stop_loss({risk["stop_loss_pct"]})')
        if risk.get("take_profit_pct"):
            lines.append(f'    .take_profit({risk["take_profit_pct"]})')
        if risk.get("trailing_stop_pct"):
            lines.append(f'    .trailing_stop({risk["trailing_stop_pct"]})')

        lines.append('    .build()')
        lines.append(')')
        lines.append('')

        # Main block
        lines.append('if __name__ == "__main__":')
        lines.append('    print(strategy.summary())')
        lines.append('')

        return '\n'.join(lines)

    @staticmethod
    def _collect_imports(definition: StrategyDefinition) -> Set[str]:
        """필요한 import 수집"""
        imports = set()

        for indicator in definition.indicators:
            ind_id = indicator.get("id", "")
            dsl_name = INDICATOR_DSL_MAP.get(ind_id, ind_id.upper())
            imports.add(dsl_name)

        # 조건에서 Price 사용 여부 확인
        if PythonExporter._uses_price(definition.entry) or PythonExporter._uses_price(definition.exit):
            imports.add("Price")

        return imports

    @staticmethod
    def _uses_price(condition_dict: Dict[str, Any]) -> bool:
        """조건에서 Price 사용 여부 확인"""
        if not condition_dict:
            return False

        conditions = condition_dict.get("conditions", [condition_dict])
        for cond in conditions:
            # 단일 조건
            indicator = cond.get("indicator", "")
            compare_to = cond.get("compare_to", "")
            indicator_def = cond.get("indicator_def", {})
            compare_def = cond.get("compare_def", {})

            if indicator in ("close", "high", "low", "open") or indicator_def.get("id") == "price":
                return True
            if compare_to in ("close", "high", "low", "open") or compare_def.get("id") == "price":
                return True

            # 중첩 조건
            if "conditions" in cond:
                if PythonExporter._uses_price(cond):
                    return True

        return False

    @staticmethod
    def _generate_indicator_vars(definition: StrategyDefinition) -> List[str]:
        """멀티 아웃풋 지표 변수 생성"""
        lines = []
        seen_aliases = set()

        for indicator in definition.indicators:
            ind_id = indicator.get("id", "")
            alias = indicator.get("alias", "")
            params = indicator.get("params", {})

            # 멀티 아웃풋 지표만 변수로 생성
            if ind_id not in MULTI_OUTPUT_INDICATORS:
                continue

            # 기본 alias에서 output 접미사 제거 (bb_20_upper -> bb_20)
            base_alias = alias
            for output in MULTI_OUTPUT_INDICATORS.get(ind_id, set()):
                if base_alias.endswith(f"_{output}"):
                    base_alias = base_alias[:-len(f"_{output}")]
                    break

            if base_alias in seen_aliases:
                continue
            seen_aliases.add(base_alias)

            dsl_name = INDICATOR_DSL_MAP.get(ind_id, ind_id.upper())
            params_str = PythonExporter._format_params(params)

            lines.append(f'{base_alias} = {dsl_name}({params_str})')

        return lines

    @staticmethod
    def _format_params(params: Dict[str, Any]) -> str:
        """파라미터를 함수 인자 문자열로 변환"""
        if not params:
            return ""

        parts = []
        for key, value in params.items():
            if isinstance(value, str) and value.startswith("$"):
                # 변수 참조
                parts.append(f'{key}={value[1:]}')
            elif isinstance(value, str):
                parts.append(f'{key}="{value}"')
            else:
                parts.append(f'{value}')

        return ', '.join(parts)

    @staticmethod
    def _generate_condition_code(
        condition_dict: Dict[str, Any],
        indicators: List[Dict[str, Any]],
    ) -> str:
        """조건을 Python DSL 코드로 변환"""
        if not condition_dict:
            return "True"

        logic = condition_dict.get("logic", "AND")
        conditions = condition_dict.get("conditions", [])

        if not conditions:
            # 단일 조건 (conditions 키가 없는 경우)
            return PythonExporter._generate_single_condition(condition_dict, indicators)

        # 복합 조건
        condition_codes = []
        for cond in conditions:
            if "conditions" in cond:
                # 중첩 조건
                nested = PythonExporter._generate_condition_code(cond, indicators)
                condition_codes.append(f'({nested})')
            else:
                code = PythonExporter._generate_single_condition(cond, indicators)
                condition_codes.append(code)

        if logic == "AND":
            return ' & '.join(condition_codes)
        elif logic == "OR":
            return ' | '.join(condition_codes)
        else:
            return ' & '.join(condition_codes)

    @staticmethod
    def _generate_single_condition(
        cond: Dict[str, Any],
        indicators: List[Dict[str, Any]],
    ) -> str:
        """단일 조건을 Python DSL 코드로 변환"""
        operator = cond.get("event", cond.get("operator", "greater_than"))
        indicator_alias = cond.get("indicator", "")
        output = cond.get("output", "value")
        compare_to = cond.get("compare_to")
        compare_output = cond.get("compare_output", "value")
        value = cond.get("value")
        indicator_def = cond.get("indicator_def", {})
        compare_def = cond.get("compare_def", {})

        # 왼쪽 피연산자 생성
        left = PythonExporter._generate_operand(
            indicator_alias, output, indicator_def, indicators
        )

        # 교차 조건
        if operator in ("cross_above", "cross_below"):
            method = ".crosses_above" if operator == "cross_above" else ".crosses_below"
            if compare_to:
                right = PythonExporter._generate_operand(
                    compare_to, compare_output, compare_def, indicators
                )
                return f'{left}{method}({right})'
            elif value is not None:
                return f'{left}{method}({value})'
            return f'{left}{method}(0)'

        # 일반 비교 조건
        op_symbol = OPERATOR_MAP.get(operator, ">")

        if compare_to:
            right = PythonExporter._generate_operand(
                compare_to, compare_output, compare_def, indicators
            )
            return f'({left} {op_symbol} {right})'
        elif value is not None:
            return f'({left} {op_symbol} {value})'

        return f'({left} {op_symbol} 0)'

    @staticmethod
    def _generate_operand(
        alias: str,
        output: str,
        indicator_def: Dict[str, Any],
        indicators: List[Dict[str, Any]],
    ) -> str:
        """피연산자 코드 생성"""
        # Price 처리
        if alias in ("close", "high", "low", "open"):
            return f'Price.{alias}()'

        if indicator_def.get("id") == "price":
            price_output = indicator_def.get("output", output)
            return f'Price.{price_output}()'

        # 지표 정의 찾기
        ind_info = None
        for ind in indicators:
            if ind.get("alias") == alias:
                ind_info = ind
                break

        if ind_info is None:
            ind_info = indicator_def

        if not ind_info:
            # 별칭만으로 추론
            return alias

        ind_id = ind_info.get("id", "")
        params = ind_info.get("params", {})

        # 멀티 아웃풋 지표
        if ind_id in MULTI_OUTPUT_INDICATORS:
            base_alias = alias
            for out in MULTI_OUTPUT_INDICATORS.get(ind_id, set()):
                if base_alias.endswith(f"_{out}"):
                    base_alias = base_alias[:-len(f"_{out}")]
                    break

            if output != "value":
                return f'{base_alias}.{output}'
            else:
                return base_alias

        # 단일 아웃풋 지표
        dsl_name = INDICATOR_DSL_MAP.get(ind_id, ind_id.upper())
        params_str = PythonExporter._format_params(params)

        return f'{dsl_name}({params_str})'

    @staticmethod
    def generate_from_rule(
        strategy_id: str,
        name: str,
        description: str,
        category: str,
        entry_condition: str,
        exit_condition: str,
        stop_loss: Optional[float] = None,
        take_profit: Optional[float] = None,
        trailing_stop: Optional[float] = None,
        imports: Optional[List[str]] = None,
    ) -> str:
        """직접 규칙을 받아서 Python 코드 생성

        조건을 이미 문자열로 가지고 있을 때 사용.

        Args:
            strategy_id: 전략 ID
            name: 전략 이름
            description: 전략 설명
            category: 카테고리
            entry_condition: 진입 조건 코드
            exit_condition: 청산 조건 코드
            stop_loss: 손절 %
            take_profit: 익절 %
            trailing_stop: 트레일링 스탑 %
            imports: 추가 import 목록
        """
        lines = []

        # 헤더
        lines.append(f'# === {strategy_id}.py ===')
        lines.append('# Generated by KIS Backtest')
        lines.append(f'# Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        # Imports
        all_imports = {"RuleBuilder"}
        if imports:
            all_imports.update(imports)

        lines.append('from kis_backtest.dsl import (')
        for imp in sorted(all_imports):
            lines.append(f'    {imp},')
        lines.append(')')
        lines.append('')

        # 전략 빌드
        lines.append('strategy = (')
        lines.append(f'    RuleBuilder("{strategy_id}")')
        lines.append(f'    .description("{description}")')
        lines.append(f'    .category("{category}")')
        lines.append(f'    .buy_when({entry_condition})')
        lines.append(f'    .sell_when({exit_condition})')

        if stop_loss:
            lines.append(f'    .stop_loss({stop_loss})')
        if take_profit:
            lines.append(f'    .take_profit({take_profit})')
        if trailing_stop:
            lines.append(f'    .trailing_stop({trailing_stop})')

        lines.append('    .build()')
        lines.append(')')
        lines.append('')

        lines.append('if __name__ == "__main__":')
        lines.append('    print(strategy.summary())')
        lines.append('')

        return '\n'.join(lines)
