/**
 * Indicator and Candlestick Pattern Constants
 * Based on Lean INDICATOR_REGISTRY (80 indicators + 63 candlestick patterns)
 */

import type { IndicatorDefinition, IndicatorCategory } from "@/types/builder";

// ============================================================
// Category Labels
// ============================================================

export const CATEGORY_LABELS: Record<IndicatorCategory, string> = {
  moving_average: "이동평균",
  oscillator: "오실레이터",
  trend: "추세",
  volume: "거래량",
  volatility: "변동성",
  misc: "기타",
  candlestick: "캔들스틱",
};;

export const CATEGORY_ORDER: IndicatorCategory[] = [
  "moving_average",
  "oscillator",
  "trend",
  "volume",
  "volatility",
  "misc",
  "candlestick",
];

// ============================================================
// Indicator Definitions (80 indicators)
// ============================================================

export const INDICATORS: IndicatorDefinition[] = [
  // ============================================================
  // Moving Averages (14)
  // ============================================================
  {
    id: "sma",
    name: "Simple Moving Average",
    nameKo: "단순 이동평균",
    category: "moving_average",
    description: "주어진 기간의 단순 평균",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "ema",
    name: "Exponential Moving Average",
    nameKo: "지수 이동평균",
    category: "moving_average",
    description: "최근 데이터에 더 큰 가중치를 부여하는 이동평균",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "dema",
    name: "Double EMA",
    nameKo: "이중 지수 이동평균",
    category: "moving_average",
    description: "EMA의 지연을 줄인 이동평균",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "tema",
    name: "Triple EMA",
    nameKo: "삼중 지수 이동평균",
    category: "moving_average",
    description: "DEMA보다 더 지연을 줄인 이동평균",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "hma",
    name: "Hull Moving Average",
    nameKo: "헐 이동평균",
    category: "moving_average",
    description: "노이즈를 줄이면서 빠른 반응을 보이는 이동평균",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "kama",
    name: "Kaufman Adaptive MA",
    nameKo: "카우프만 적응형",
    category: "moving_average",
    description: "시장 변동성에 따라 민감도가 조절되는 이동평균",
    params: [{ name: "period", type: "number", default: 10, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "alma",
    name: "Arnaud Legoux MA",
    nameKo: "아르노 르구",
    category: "moving_average",
    description: "가우시안 필터를 사용한 이동평균",
    params: [
      { name: "period", type: "number", default: 9, min: 1, max: 500 },
      { name: "sigma", type: "number", default: 6, min: 0.1, max: 20 },
      { name: "offset", type: "number", default: 0.85, min: 0, max: 1, step: 0.05 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "lwma",
    name: "Linear Weighted MA",
    nameKo: "선형 가중 이동평균",
    category: "moving_average",
    description: "최근 데이터에 선형적으로 큰 가중치를 부여",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "trima",
    name: "Triangular MA",
    nameKo: "삼각 이동평균",
    category: "moving_average",
    description: "중간 데이터에 더 큰 가중치를 부여하는 이동평균",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "t3",
    name: "T3 Moving Average",
    nameKo: "T3 이동평균",
    category: "moving_average",
    description: "부드러운 곡선을 만드는 고급 이동평균",
    params: [
      { name: "period", type: "number", default: 10, min: 1, max: 500 },
      { name: "volume_factor", type: "number", default: 0.7, min: 0, max: 1, step: 0.1 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "zlema",
    name: "Zero Lag EMA",
    nameKo: "제로 래그 EMA",
    category: "moving_average",
    description: "지연을 최소화한 지수 이동평균",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "wma",
    name: "Wilder Moving Average",
    nameKo: "와일더 이동평균",
    category: "moving_average",
    description: "RSI, ATR에서 사용되는 와일더의 이동평균",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "frama",
    name: "Fractal Adaptive MA",
    nameKo: "프랙탈 적응형",
    category: "moving_average",
    description: "프랙탈 차원을 기반으로 조절되는 이동평균",
    params: [{ name: "period", type: "number", default: 16, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "vidya",
    name: "VIDYA",
    nameKo: "VIDYA",
    category: "moving_average",
    description: "변동 지수 동적 평균",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },

  // ============================================================
  // Oscillators (20)
  // ============================================================
  {
    id: "rsi",
    name: "RSI",
    nameKo: "RSI",
    category: "oscillator",
    description: "상대강도지수 (0-100)",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "stochastic",
    name: "Stochastic",
    nameKo: "스토캐스틱",
    category: "oscillator",
    description: "스토캐스틱 오실레이터 (%K, %D)",
    params: [
      { name: "k_period", type: "number", default: 14, min: 1, max: 100 },
      { name: "d_period", type: "number", default: 3, min: 1, max: 100 },
    ],
    outputs: [
      { id: "k", name: "%K" },
      { id: "d", name: "%D" },
    ],
    defaultOutput: "k",
  },
  {
    id: "stochrsi",
    name: "Stochastic RSI",
    nameKo: "스토캐스틱 RSI",
    category: "oscillator",
    description: "RSI에 스토캐스틱을 적용한 지표",
    params: [
      { name: "rsi_period", type: "number", default: 14, min: 1, max: 100 },
      { name: "stoch_period", type: "number", default: 14, min: 1, max: 100 },
      { name: "k_period", type: "number", default: 3, min: 1, max: 100 },
      { name: "d_period", type: "number", default: 3, min: 1, max: 100 },
    ],
    outputs: [
      { id: "k", name: "%K" },
      { id: "d", name: "%D" },
    ],
    defaultOutput: "k",
  },
  {
    id: "macd",
    name: "MACD",
    nameKo: "MACD",
    category: "oscillator",
    description: "이동평균 수렴/발산 지표",
    params: [
      { name: "fast", type: "number", default: 12, min: 1, max: 100 },
      { name: "slow", type: "number", default: 26, min: 1, max: 200 },
      { name: "signal", type: "number", default: 9, min: 1, max: 100 },
    ],
    outputs: [
      { id: "value", name: "MACD" },
      { id: "signal", name: "시그널" },
      { id: "histogram", name: "히스토그램" },
    ],
    defaultOutput: "value",
  },
  {
    id: "cci",
    name: "CCI",
    nameKo: "CCI",
    category: "oscillator",
    description: "상품채널지수",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "williams_r",
    name: "Williams %R",
    nameKo: "윌리엄스 %R",
    category: "oscillator",
    description: "윌리엄스 %R (-100~0)",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "momentum",
    name: "Momentum",
    nameKo: "모멘텀",
    category: "oscillator",
    description: "가격 변화율 (백분율)",
    params: [{ name: "period", type: "number", default: 10, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "roc",
    name: "Rate of Change",
    nameKo: "변화율",
    category: "oscillator",
    description: "가격 변화율",
    params: [{ name: "period", type: "number", default: 10, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "apo",
    name: "APO",
    nameKo: "APO",
    category: "oscillator",
    description: "절대 가격 오실레이터",
    params: [
      { name: "fast", type: "number", default: 12, min: 1, max: 100 },
      { name: "slow", type: "number", default: 26, min: 1, max: 200 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "ppo",
    name: "PPO",
    nameKo: "PPO",
    category: "oscillator",
    description: "백분율 가격 오실레이터",
    params: [
      { name: "fast", type: "number", default: 12, min: 1, max: 100 },
      { name: "slow", type: "number", default: 26, min: 1, max: 200 },
    ],
    outputs: [
      { id: "value", name: "PPO" },
      { id: "signal", name: "시그널" },
      { id: "histogram", name: "히스토그램" },
    ],
    defaultOutput: "value",
  },
  {
    id: "aroon",
    name: "Aroon",
    nameKo: "아룬",
    category: "oscillator",
    description: "아룬 오실레이터",
    params: [
      { name: "up_period", type: "number", default: 25, min: 1, max: 100 },
      { name: "down_period", type: "number", default: 25, min: 1, max: 100 },
    ],
    outputs: [
      { id: "value", name: "오실레이터" },
      { id: "aroon_up", name: "Aroon Up" },
      { id: "aroon_down", name: "Aroon Down" },
    ],
    defaultOutput: "value",
  },
  {
    id: "cmo",
    name: "CMO",
    nameKo: "CMO",
    category: "oscillator",
    description: "챈드 모멘텀 오실레이터",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "ao",
    name: "Awesome Oscillator",
    nameKo: "AO",
    category: "oscillator",
    description: "오썸 오실레이터",
    params: [
      { name: "fast", type: "number", default: 5, min: 1, max: 100 },
      { name: "slow", type: "number", default: 34, min: 1, max: 200 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "cho",
    name: "Chaikin Oscillator",
    nameKo: "채킨 오실레이터",
    category: "oscillator",
    description: "채킨 오실레이터",
    params: [
      { name: "fast", type: "number", default: 3, min: 1, max: 100 },
      { name: "slow", type: "number", default: 10, min: 1, max: 200 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "ultosc",
    name: "Ultimate Oscillator",
    nameKo: "궁극 오실레이터",
    category: "oscillator",
    description: "궁극 오실레이터",
    params: [
      { name: "period1", type: "number", default: 7, min: 1, max: 100 },
      { name: "period2", type: "number", default: 14, min: 1, max: 100 },
      { name: "period3", type: "number", default: 28, min: 1, max: 200 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "trix",
    name: "TRIX",
    nameKo: "TRIX",
    category: "oscillator",
    description: "TRIX 오실레이터",
    params: [{ name: "period", type: "number", default: 15, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "tsi",
    name: "TSI",
    nameKo: "TSI",
    category: "oscillator",
    description: "참 강도 지수",
    params: [
      { name: "long_period", type: "number", default: 25, min: 1, max: 100 },
      { name: "short_period", type: "number", default: 13, min: 1, max: 100 },
      { name: "signal_period", type: "number", default: 7, min: 1, max: 100 },
    ],
    outputs: [
      { id: "value", name: "TSI" },
      { id: "signal", name: "시그널" },
    ],
    defaultOutput: "value",
  },
  {
    id: "rvi",
    name: "RVI",
    nameKo: "RVI",
    category: "oscillator",
    description: "상대 활력 지수",
    params: [{ name: "period", type: "number", default: 10, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "dpo",
    name: "DPO",
    nameKo: "DPO",
    category: "oscillator",
    description: "추세 제거 가격 오실레이터",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "kvo",
    name: "Klinger Volume",
    nameKo: "클링거 거래량",
    category: "oscillator",
    description: "클링거 거래량 오실레이터",
    params: [
      { name: "fast", type: "number", default: 34, min: 1, max: 100 },
      { name: "slow", type: "number", default: 55, min: 1, max: 200 },
      { name: "signal", type: "number", default: 13, min: 1, max: 100 },
    ],
    outputs: [
      { id: "value", name: "KVO" },
      { id: "signal", name: "시그널" },
    ],
    defaultOutput: "value",
  },

  // ============================================================
  // Trend Indicators (12)
  // ============================================================
  {
    id: "adx",
    name: "ADX",
    nameKo: "ADX",
    category: "trend",
    description: "평균방향지수 (추세 강도)",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [
      { id: "value", name: "ADX" },
      { id: "plus_di", name: "+DI" },
      { id: "minus_di", name: "-DI" },
    ],
    defaultOutput: "value",
  },
  {
    id: "adxr",
    name: "ADXR",
    nameKo: "ADXR",
    category: "trend",
    description: "평균방향운동등급",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "ichimoku",
    name: "Ichimoku",
    nameKo: "일목균형표",
    category: "trend",
    description: "일목균형표 (텐칸, 기준, 선행A/B, 후행)",
    params: [
      { name: "tenkan", type: "number", default: 9, min: 1, max: 100 },
      { name: "kijun", type: "number", default: 26, min: 1, max: 200 },
      { name: "senkou_b", type: "number", default: 52, min: 1, max: 300 },
    ],
    outputs: [
      { id: "tenkan", name: "텐칸선" },
      { id: "kijun", name: "기준선" },
      { id: "senkou_a", name: "선행 A" },
      { id: "senkou_b", name: "선행 B" },
      { id: "chikou", name: "후행" },
    ],
    defaultOutput: "tenkan",
  },
  {
    id: "sar",
    name: "Parabolic SAR",
    nameKo: "파라볼릭 SAR",
    category: "trend",
    description: "파라볼릭 스탑 앤 리버스",
    params: [
      { name: "af_start", type: "number", default: 0.02, min: 0.01, max: 0.2, step: 0.01 },
      { name: "af_step", type: "number", default: 0.02, min: 0.01, max: 0.2, step: 0.01 },
      { name: "af_max", type: "number", default: 0.2, min: 0.1, max: 0.5, step: 0.05 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "vortex",
    name: "Vortex",
    nameKo: "볼텍스",
    category: "trend",
    description: "볼텍스 지표 (+VI, -VI)",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [
      { id: "plus_vi", name: "+VI" },
      { id: "minus_vi", name: "-VI" },
    ],
    defaultOutput: "plus_vi",
  },
  {
    id: "chop",
    name: "Choppiness Index",
    nameKo: "혼잡 지수",
    category: "trend",
    description: "시장의 혼잡 정도 (0-100)",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "kst",
    name: "KST",
    nameKo: "KST",
    category: "trend",
    description: "Know Sure Thing",
    params: [
      { name: "roc1", type: "number", default: 10, min: 1, max: 100 },
      { name: "roc2", type: "number", default: 15, min: 1, max: 100 },
      { name: "roc3", type: "number", default: 20, min: 1, max: 100 },
      { name: "roc4", type: "number", default: 30, min: 1, max: 100 },
    ],
    outputs: [
      { id: "value", name: "KST" },
      { id: "signal", name: "시그널" },
    ],
    defaultOutput: "value",
  },
  {
    id: "coppock",
    name: "Coppock Curve",
    nameKo: "코폭 곡선",
    category: "trend",
    description: "코폭 곡선",
    params: [
      { name: "short_roc", type: "number", default: 11, min: 1, max: 100 },
      { name: "long_roc", type: "number", default: 14, min: 1, max: 100 },
      { name: "wma", type: "number", default: 10, min: 1, max: 100 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "supertrend",
    name: "SuperTrend",
    nameKo: "슈퍼트렌드",
    category: "trend",
    description: "슈퍼트렌드 지표",
    params: [
      { name: "period", type: "number", default: 10, min: 1, max: 100 },
      { name: "multiplier", type: "number", default: 3, min: 0.5, max: 10, step: 0.5 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "mass_index",
    name: "Mass Index",
    nameKo: "매스 인덱스",
    category: "trend",
    description: "매스 인덱스",
    params: [
      { name: "ema_period", type: "number", default: 9, min: 1, max: 100 },
      { name: "sum_period", type: "number", default: 25, min: 1, max: 100 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "schaff",
    name: "Schaff Trend Cycle",
    nameKo: "샤프 추세 사이클",
    category: "trend",
    description: "샤프 추세 사이클",
    params: [
      { name: "cycle", type: "number", default: 10, min: 1, max: 100 },
      { name: "fast", type: "number", default: 23, min: 1, max: 100 },
      { name: "slow", type: "number", default: 50, min: 1, max: 200 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "fisher",
    name: "Fisher Transform",
    nameKo: "피셔 변환",
    category: "trend",
    description: "피셔 변환",
    params: [{ name: "period", type: "number", default: 10, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },

  // ============================================================
  // Volume Indicators (12)
  // ============================================================
  {
    id: "obv",
    name: "OBV",
    nameKo: "OBV",
    category: "volume",
    description: "거래량 균형 지표",
    params: [],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "ad",
    name: "A/D",
    nameKo: "누적/분산",
    category: "volume",
    description: "누적/분산 지표",
    params: [],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "adl",
    name: "A/D Line",
    nameKo: "누적/분산 라인",
    category: "volume",
    description: "누적/분산 라인",
    params: [],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "cmf",
    name: "CMF",
    nameKo: "채킨 MF",
    category: "volume",
    description: "채킨 머니플로우",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "mfi",
    name: "MFI",
    nameKo: "MFI",
    category: "volume",
    description: "자금흐름지수 (0-100)",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "force",
    name: "Force Index",
    nameKo: "포스 인덱스",
    category: "volume",
    description: "포스 인덱스",
    params: [{ name: "period", type: "number", default: 13, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "vwap",
    name: "VWAP",
    nameKo: "VWAP",
    category: "volume",
    description: "거래량 가중 평균가",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "vwma",
    name: "VWMA",
    nameKo: "VWMA",
    category: "volume",
    description: "거래량 가중 이동평균",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "eom",
    name: "Ease of Movement",
    nameKo: "움직임의 용이성",
    category: "volume",
    description: "움직임의 용이성",
    params: [
      { name: "period", type: "number", default: 14, min: 1, max: 100 },
      { name: "scale", type: "number", default: 10000, min: 1, max: 100000 },
    ],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },

  // ============================================================
  // Volatility Indicators (10)
  // ============================================================
  {
    id: "atr",
    name: "ATR",
    nameKo: "ATR",
    category: "volatility",
    description: "평균진폭",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "natr",
    name: "NATR",
    nameKo: "NATR",
    category: "volatility",
    description: "정규화 ATR",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "bollinger",
    name: "Bollinger Bands",
    nameKo: "볼린저 밴드",
    category: "volatility",
    description: "볼린저 밴드 (상단, 중단, 하단)",
    params: [
      { name: "period", type: "number", default: 20, min: 1, max: 100 },
      { name: "std", type: "number", default: 2, min: 0.5, max: 5, step: 0.5 },
    ],
    outputs: [
      { id: "upper", name: "상단" },
      { id: "middle", name: "중단" },
      { id: "lower", name: "하단" },
    ],
    defaultOutput: "middle",
  },
  {
    id: "keltner",
    name: "Keltner Channels",
    nameKo: "켈트너 채널",
    category: "volatility",
    description: "켈트너 채널 (상단, 중단, 하단)",
    params: [
      { name: "period", type: "number", default: 20, min: 1, max: 100 },
      { name: "multiplier", type: "number", default: 2, min: 0.5, max: 5, step: 0.5 },
    ],
    outputs: [
      { id: "upper", name: "상단" },
      { id: "middle", name: "중단" },
      { id: "lower", name: "하단" },
    ],
    defaultOutput: "middle",
  },
  {
    id: "donchian",
    name: "Donchian Channel",
    nameKo: "돈치안 채널",
    category: "volatility",
    description: "돈치안 채널 (상단, 하단)",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 100 }],
    outputs: [
      { id: "upper", name: "상단" },
      { id: "lower", name: "하단" },
    ],
    defaultOutput: "upper",
  },
  {
    id: "std",
    name: "Standard Deviation",
    nameKo: "표준편차",
    category: "volatility",
    description: "표준편차",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "variance",
    name: "Variance",
    nameKo: "분산",
    category: "volatility",
    description: "분산",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "accbands",
    name: "Acceleration Bands",
    nameKo: "가속 밴드",
    category: "volatility",
    description: "가속 밴드 (상단, 중단, 하단)",
    params: [
      { name: "period", type: "number", default: 20, min: 1, max: 100 },
      { name: "width", type: "number", default: 4, min: 1, max: 10 },
    ],
    outputs: [
      { id: "upper", name: "상단" },
      { id: "middle", name: "중단" },
      { id: "lower", name: "하단" },
    ],
    defaultOutput: "middle",
  },
  {
    id: "beta",
    name: "Beta",
    nameKo: "베타",
    category: "volatility",
    description: "베타 (벤치마크 대비 변동성)",
    params: [{ name: "period", type: "number", default: 252, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "alpha",
    name: "Alpha",
    nameKo: "알파",
    category: "volatility",
    description: "알파 (벤치마크 대비 초과수익)",
    params: [{ name: "period", type: "number", default: 252, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },

  // ============================================================
  // Misc Indicators (10)
  // ============================================================
  {
    id: "maximum",
    name: "Maximum",
    nameKo: "최고가",
    category: "misc",
    description: "기간 내 최고가",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "minimum",
    name: "Minimum",
    nameKo: "최저가",
    category: "misc",
    description: "기간 내 최저가",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "midpoint",
    name: "Mid Point",
    nameKo: "중간값",
    category: "misc",
    description: "중간값",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "midprice",
    name: "Mid Price",
    nameKo: "중간가격",
    category: "misc",
    description: "중간가격",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "logr",
    name: "Log Return",
    nameKo: "로그 수익률",
    category: "misc",
    description: "로그 수익률",
    params: [{ name: "period", type: "number", default: 1, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "ibs",
    name: "IBS",
    nameKo: "IBS",
    category: "misc",
    description: "내부 바 강도",
    params: [],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "bop",
    name: "Balance of Power",
    nameKo: "힘의 균형",
    category: "misc",
    description: "힘의 균형",
    params: [],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "regression",
    name: "Linear Regression",
    nameKo: "선형 회귀",
    category: "misc",
    description: "선형 회귀",
    params: [{ name: "period", type: "number", default: 14, min: 1, max: 100 }],
    outputs: [
      { id: "value", name: "값" },
      { id: "slope", name: "기울기" },
      { id: "intercept", name: "절편" },
    ],
    defaultOutput: "value",
  },
  {
    id: "pivot",
    name: "Pivot Points",
    nameKo: "피봇 포인트",
    category: "misc",
    description: "피봇 포인트",
    params: [
      { name: "left_bars", type: "number", default: 5, min: 1, max: 100 },
      { name: "right_bars", type: "number", default: 5, min: 1, max: 100 },
    ],
    outputs: [
      { id: "high", name: "고가" },
      { id: "low", name: "저가" },
    ],
    defaultOutput: "high",
  },
  {
    id: "augen",
    name: "Augen Price Spike",
    nameKo: "오겐 스파이크",
    category: "misc",
    description: "오겐 가격 스파이크",
    params: [{ name: "period", type: "number", default: 3, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "consecutive",
    name: "Consecutive Days",
    nameKo: "연속 상승/하락",
    category: "misc",
    description: "연속 상승 또는 하락 일수 계산",
    params: [{ name: "direction", type: "string", default: "up", description: "up 또는 down" }],
    outputs: [{ id: "value", name: "일수" }],
    defaultOutput: "value",
  },
  {
    id: "disparity",
    name: "Disparity Index",
    nameKo: "이격도",
    category: "misc",
    description: "현재가 / 이동평균 * 100 (100 = 평균과 동일)",
    params: [{ name: "period", type: "number", default: 20, min: 1, max: 200 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "volatility_ind",
    name: "Volatility",
    nameKo: "변동성",
    category: "volatility",
    description: "일간 수익률의 표준편차",
    params: [{ name: "period", type: "number", default: 10, min: 1, max: 100 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "change",
    name: "Daily Change",
    nameKo: "전일대비 등락률",
    category: "misc",
    description: "전일 대비 등락률 (%)",
    params: [],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
  {
    id: "returns",
    name: "Returns",
    nameKo: "수익률",
    category: "misc",
    description: "기간 수익률 (백분율)",
    params: [{ name: "period", type: "number", default: 60, min: 1, max: 500 }],
    outputs: [{ id: "value", name: "값" }],
    defaultOutput: "value",
  },
];

// ============================================================
// Candlestick Patterns (63)
// ============================================================

export const CANDLESTICK_PATTERNS: IndicatorDefinition[] = [
  // Single candle patterns (15)
  { id: "doji", name: "Doji", nameKo: "도지", category: "candlestick", description: "우유부단 (시가=종가)", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "dragonfly_doji", name: "Dragonfly Doji", nameKo: "잠자리 도지", category: "candlestick", description: "긴 아래꼬리, 상승 반전", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "gravestone_doji", name: "Gravestone Doji", nameKo: "비석 도지", category: "candlestick", description: "긴 위꼬리, 하락 반전", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "long_legged_doji", name: "Long Legged Doji", nameKo: "긴다리 도지", category: "candlestick", description: "극심한 우유부단", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "hammer", name: "Hammer", nameKo: "망치형", category: "candlestick", description: "상승 반전 신호", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "hanging_man", name: "Hanging Man", nameKo: "교수형", category: "candlestick", description: "하락 반전 신호", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "inverted_hammer", name: "Inverted Hammer", nameKo: "역망치형", category: "candlestick", description: "상승 반전 신호", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "shooting_star", name: "Shooting Star", nameKo: "유성형", category: "candlestick", description: "하락 반전 신호", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "marubozu", name: "Marubozu", nameKo: "장대봉", category: "candlestick", description: "강한 추세", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "closing_marubozu", name: "Closing Marubozu", nameKo: "종가 장대봉", category: "candlestick", description: "종가 장대봉", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "spinning_top", name: "Spinning Top", nameKo: "팽이형", category: "candlestick", description: "팽이형", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "belt_hold", name: "Belt Hold", nameKo: "띠 잡기", category: "candlestick", description: "띠 잡기", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "high_wave", name: "High Wave Candle", nameKo: "큰 파도", category: "candlestick", description: "큰 파도", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "rickshaw_man", name: "Rickshaw Man", nameKo: "인력거꾼", category: "candlestick", description: "인력거꾼", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },

  // Double candle patterns (20)
  { id: "engulfing", name: "Engulfing", nameKo: "장악형", category: "candlestick", description: "강한 반전 신호", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "harami", name: "Harami", nameKo: "잉태형", category: "candlestick", description: "잉태형", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "harami_cross", name: "Harami Cross", nameKo: "잉태 십자형", category: "candlestick", description: "잉태 십자형", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "piercing", name: "Piercing", nameKo: "관통형", category: "candlestick", description: "관통형 (상승 반전)", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "dark_cloud_cover", name: "Dark Cloud Cover", nameKo: "먹구름형", category: "candlestick", description: "먹구름형 (하락 반전)", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "counterattack", name: "Counterattack", nameKo: "반격형", category: "candlestick", description: "반격형", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "on_neck", name: "On Neck", nameKo: "목 위", category: "candlestick", description: "목 위", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "in_neck", name: "In Neck", nameKo: "목 안", category: "candlestick", description: "목 안", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "thrusting", name: "Thrusting", nameKo: "밀어붙이기", category: "candlestick", description: "밀어붙이기", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "separating_lines", name: "Separating Lines", nameKo: "분리선", category: "candlestick", description: "분리선", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "kicking", name: "Kicking", nameKo: "킥킹", category: "candlestick", description: "강한 갭", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "matching_low", name: "Matching Low", nameKo: "일치 저가", category: "candlestick", description: "일치 저가", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "gap_side_by_side_white", name: "Gap Side By Side White", nameKo: "갭 나란히", category: "candlestick", description: "갭 나란히", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "homing_pigeon", name: "Homing Pigeon", nameKo: "귀소비둘기", category: "candlestick", description: "귀소비둘기", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "dojistar", name: "Doji Star", nameKo: "도지별", category: "candlestick", description: "도지별", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },

  // Triple+ candle patterns (28)
  { id: "morning_star", name: "Morning Star", nameKo: "샛별형", category: "candlestick", description: "강한 상승 반전", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "morning_doji_star", name: "Morning Doji Star", nameKo: "샛별 도지", category: "candlestick", description: "샛별 도지", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "evening_star", name: "Evening Star", nameKo: "저녁별형", category: "candlestick", description: "강한 하락 반전", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "evening_doji_star", name: "Evening Doji Star", nameKo: "저녁별 도지", category: "candlestick", description: "저녁별 도지", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "three_white_soldiers", name: "Three White Soldiers", nameKo: "적삼병", category: "candlestick", description: "강한 상승 신호", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "three_black_crows", name: "Three Black Crows", nameKo: "흑삼병", category: "candlestick", description: "강한 하락 신호", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "three_inside", name: "Three Inside", nameKo: "삼내형", category: "candlestick", description: "삼내형", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "three_outside", name: "Three Outside", nameKo: "삼외형", category: "candlestick", description: "삼외형", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "abandoned_baby", name: "Abandoned Baby", nameKo: "버려진 아기", category: "candlestick", description: "버려진 아기", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "three_stars_in_south", name: "Three Stars In South", nameKo: "남쪽 삼성", category: "candlestick", description: "남쪽 삼성", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "advance_block", name: "Advance Block", nameKo: "진행 차단", category: "candlestick", description: "진행 차단", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "stalled_pattern", name: "Stalled Pattern", nameKo: "정체", category: "candlestick", description: "정체", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "tasuki_gap", name: "Tasuki Gap", nameKo: "타스키 갭", category: "candlestick", description: "타스키 갭", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "upside_gap_two_crows", name: "Upside Gap Two Crows", nameKo: "갭업 두 까마귀", category: "candlestick", description: "갭업 두 까마귀", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "three_line_strike", name: "Three Line Strike", nameKo: "삼선 타격", category: "candlestick", description: "삼선 타격", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "unique_three_river", name: "Unique Three River", nameKo: "독특한 삼강", category: "candlestick", description: "독특한 삼강", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "breakaway", name: "Breakaway", nameKo: "이탈형", category: "candlestick", description: "이탈형 (5일)", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "mat_hold", name: "Mat Hold", nameKo: "매트 홀드", category: "candlestick", description: "매트 홀드 (5일)", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "rising_three_methods", name: "Rising Three Methods", nameKo: "상승 삼법", category: "candlestick", description: "상승 삼법 (5일)", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "falling_three_methods", name: "Falling Three Methods", nameKo: "하락 삼법", category: "candlestick", description: "하락 삼법 (5일)", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "ladder_bottom", name: "Ladder Bottom", nameKo: "사다리 바닥", category: "candlestick", description: "사다리 바닥 (5일)", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "concealing_baby_swallow", name: "Concealing Baby Swallow", nameKo: "숨긴 아기 제비", category: "candlestick", description: "숨긴 아기 제비", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "stick_sandwich", name: "Stick Sandwich", nameKo: "스틱 샌드위치", category: "candlestick", description: "스틱 샌드위치", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "tristar", name: "TriStar", nameKo: "삼성", category: "candlestick", description: "삼성 패턴", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "identical_three_crows", name: "Identical Three Crows", nameKo: "동일 흑삼병", category: "candlestick", description: "동일 흑삼병", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "two_crows", name: "Two Crows", nameKo: "두 까마귀", category: "candlestick", description: "두 까마귀", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "up_down_gap_three_methods", name: "Up/Down Gap Three Methods", nameKo: "갭 삼법", category: "candlestick", description: "갭 삼법", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
  { id: "kicking_by_length", name: "Kicking By Length", nameKo: "길이 기준 키킹", category: "candlestick", description: "길이 기준 킥킹 패턴", params: [], outputs: [{ id: "value", name: "신호" }], defaultOutput: "value" },
];

// ============================================================
// Combined All Indicators
// ============================================================

// Note: CANDLESTICK_PATTERNS removed - backend (LeanCodeGenerator) does not support them
// Use only technical indicators for backtest compatibility
export const ALL_INDICATORS: IndicatorDefinition[] = [
  ...INDICATORS,
  ...CANDLESTICK_PATTERNS,
];;

// ============================================================
// Helper Functions
// ============================================================

export function getIndicatorById(id: string): IndicatorDefinition | undefined {
  return ALL_INDICATORS.find((i) => i.id === id);
}

export function getIndicatorsByCategory(category: IndicatorCategory): IndicatorDefinition[] {
  return ALL_INDICATORS.filter((i) => i.category === category);
}

export function searchIndicators(query: string): IndicatorDefinition[] {
  const lowerQuery = query.toLowerCase();
  return ALL_INDICATORS.filter(
    (i) =>
      i.id.toLowerCase().includes(lowerQuery) ||
      i.name.toLowerCase().includes(lowerQuery) ||
      i.nameKo.includes(lowerQuery)
  );
}

// Price fields for condition operands
export const PRICE_FIELDS = [
  { id: "close", name: "종가" },
  { id: "open", name: "시가" },
  { id: "high", name: "고가" },
  { id: "low", name: "저가" },
] as const;
